name: Binance Harry Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python -m playwright install chromium

      - env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BINANCE_PROFILE: ${{ secrets.BINANCE_PROFILE }}
        run: python app.py
